$schema: https://raw.githubusercontent.com/zokugun/artifact/v0.12.0/schemas/v4/install.json
artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.15.7
    requires:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.11.9
  "@daiyam/artifact-npm":
    version: 0.8.20
  "@daiyam/artifact-npm-ts":
    version: 0.6.7
  "@daiyam/artifact-npm-cli-ts":
    version: 0.9.5
  "@daiyam/artifact-npm-zokugun":
    version: 0.3.6
  "@daiyam/artifact-test-vitest-ts":
    version: 0.6.6
    features:
      - test
  "@daiyam/artifact-gh-issuehub":
    version: 0.6.6
