artifacts:
  "@daiyam/artifact-lang-js":
    version: 0.8.4
    provides:
      - "20"
  "@daiyam/artifact-lang-ts":
    version: 0.6.1
  "@daiyam/artifact-npm":
    version: 0.6.1
  "@daiyam/artifact-npm-ts":
    version: 0.4.1
  "@daiyam/artifact-npm-cli-ts":
    version: 0.4.0
  "@daiyam/artifact-npm-zokugun":
    version: 0.2.2
  "@daiyam/artifact-test-vitest-ts":
    version: 0.2.1
  "@daiyam/artifact-gh-issuehub":
    version: 0.2.1
