name: Pre-Discussed and Approved Topics
description: |-
  Only for topics already discussed and approved in the GitHub Discussions section.
body:
  - type: markdown
    attributes:
      value: |-
        This project doesn't accept Issues directly. Please prefer GitHub Discussions. See: https://github.com/zokugun/tsc-leda/issues/1
  - type: checkboxes
    id: checkbox
    attributes:
      label: 'Sanity check'
      options:
        - label: |-
            I read https://github.com/zokugun/tsc-leda/issues/1
          required: true
  - type: textarea
    id: body
    attributes:
      label: Body
      value: |-
        DON'T OPEN NEW ISSUES DIRECTLY, PLEASE USE THE DISCUSSIONS SECTION.

        I DIDN'T READ THE ABOVE LINE. PLEASE CLOSE THIS ISSUE.
    validations:
      required: true
